const placeNames = [
  "Monumen Nasional",
  "Kota Tua",
  "Dunia Fantasi",
  "Taman Mini Indonesia Indah (TMII)",
  "Atlantis Water Adventure",
  "Taman Impian Jaya Ancol",
  "Kebun Binatang Ragunan",
  "Ocean Ecopark",
  "Pelabuhan Marina",
  "Pulau Tidung",
  "Pulau Bidadari",
  "Pulau Pari",
  "Pulau Pramuka",
  "Pulau Pelangi",
  "Pasar Seni",
  "Jembatan Kota Intan",
  "Museum Fatahillah",
  "Museum Bank Indonesia",
  "Kidzania",
  "Museum Taman Prasasti",
  "Museum Wayang",
  "Masjid Istiqlal",
  "Gereja Katedral",
  "Museum Nasional",
  "Pasar Tanah Abang",
  "Pecinan Glodok",
  "Sea World",
  "Wisata Agro Edukatif Istana Susu Cibugary",
  "Wisata Kuliner Pecenongan",
  "Taman Menteng",
  "Wisata Alam Mangrove Angke",
  "Setu Babakan",
  "Taman Suropati",
  "Pasar Taman Puring",
  "Grand Indonesia Mall",
  "Skyrink - Mall Taman Anggrek",
  "Bumi Perkemahan Cibubur",
  "Istana Negara Republik Indonesia",
  "Museum Macan (Modern and Contemporary Art in Nusantara)",
  "Galeri Nasional Indonesia",
  "Museum Bahari Jakarta",
  "Museum Seni Rupa dan Kramik",
  "The Escape Hunt",
  "Monumen Selamat Datang",
  "Jakarta Aquarium dan Safari",
  "Pulau Semak Daun",
  "Taman Situ Lembang",
  "Taman Ismail Marzuki",
  "Galeri Indonesia Kaya",
  "Museum Joang 45",
  "Jakarta Planetarium",
  "Kampung Cina",
  "Rumah Sipitung",
  "Taman Agrowisata Cilangkap",
  "Klenteng Jin De Yuan",
  "Pantai Ancol",
  "Taman Lapangan Banteng",
  "Taman Ayodya",
  "Museum Sumpah Pemuda",
  "Museum Tekstil",
  "Tugu Proklamasi",
  "Taman Legenda Keong Emas",
  "Museum Kebangkitan Nasional",
  "Museum Sasmita Loka Ahmad Yani",
  "Museum Basoeki Abdullah",
  "Museum Layang-layang",
  "Margasatwa Muara Angke",
  "Pasar Petak Sembilan",
  "Freedom Library",
  "Perpustakaan Nasional",
  "Cibubur Garden Diary (Cibugary)",
  "Waterboom PIK (Pantai Indah Kapuk)",
  "Museum Perangko",
  "Museum Tengah Kebun",
  "SnowBay Waterpark",
  "Taman Cattleya",
  "Taman Hutan Tebet",
  "Hutan Kota Srengseng",
  "Taman Spathodea",
  "Plaza Indonesia",
  "Mall Thamrin City",
  "Museum Satria Mandala",
  "Alive Museum Ancol",
  "Kawasan Kuliner BSM",
  "Taman Pintar Yogyakarta",
  "Keraton Yogyakarta",
  "Sindu Kusuma Edupark (SKE)",
  "Museum Benteng Vredeburg Yogyakarta",
  "De Mata Museum Jogja",
  "Kampung Wisata Taman Sari",
  "Situs Warungboto",
  "Nol Kilometer Jl.Malioboro",
  "Gembira Loka Zoo",
  "Sumur Gumuling",
  "Desa Wisata Sungai Code Jogja Kota",
  "Alun Alun Selatan Yogyakarta",
  "Monumen Yogya Kembali",
  "Taman Pelangi Yogyakarta",
  "Kampung Wisata Kadipaten",
  "Taman Budaya Yogyakarta",
  "Kampung Wisata Sosro Menduran",
  "Monumen Batik Yogyakarta",
  "Tugu Pal Putih Jogja",
  "Tebing Breksi",
  "Candi Donotirto",
  "Kawasan Malioboro",
  "Bangsal Pagelaran",
  "Embung Tambakboyo",
  "Hutan Pinus Pengger",
  "Monumen Serangan Umum 1 Maret",
  "Puncak Pinus Becici",
  "Bukit Bintang Yogyakarta",
  "Gedung Agung Yogyakarta",
  "The Lost World Castle",
  "Monumen Sanapati",
  "Jurang Tembelan Kanigoro",
  "The World Landmarks - Merapi Park Yogyakarta",
  "Museum Sonobudoyo Unit I",
  "Lava Bantal",
  "Bukit Panguk Kediwung",
  "Candi Prambanan",
  "Watu Goyang",
  "Kampung Wisata Rejowinangun",
  "Kauman Pakualaman Yogyakarta",
  "Alun-alun Utara Keraton Yogyakarta",
  "Pantai Goa Cemara",
  "Blue Lagoon Jogja",
  "Gumuk Pasir Parangkusumo",
  "Bukit Lintang Sewu",
  "Studio Alam Gamplong",
  "Watu Lumbung",
  "Air Terjun Kedung Pedut",
  "Puncak Kebun Buah Mangunan",
  "Desa Wisata Gamplong",
  "Kawasan Wisata Sosrowijayan",
  "Grojogan Watu Purbo Bangunrejo",
  "Wisata Alam Kalibiru",
  "Jogja Exotarium",
  "Puncak Gunung Api Purba - Nglanggeran",
  "Bendung Lepen",
  "Bunker Kaliadem Merapi",
  "Ledok Sambi",
  "Seribu Batu Songgo Langit",
  "Goa Jomblang",
  "Desa Wisata Rumah Domes/Teletubbies",
  "Bukit Wisata Pulepayung",
  "Bentara Budaya Yogyakarta (BBY)",
  "Goa Rancang Kencono",
  "Goa Cerme",
  "Wisata Kraton Jogja",
  "Desa Wisata Kelor",
  "Pantai Patihan",
  "Pantai Kukup",
  "Pantai Ngrawe (Mesra)",
  "Pantai Ngobaran",
  "Pantai Pulang Sawal",
  "Pantai Baron",
  "Pantai Pok Tunggal",
  "Hutan Pinus Asri",
  "Pasar Kebon Empring Bintaran",
  "Bukit Paralayang, Watugupit",
  "Kampung Wisata Dipowinatan",
  "Watu Mabur Mangunan",
  "Pintoe Langit Dahromo",
  "Green Village Gedangsari",
  "Kebun Teh Nglinggo",
  "Geoforest Watu Payung Turunan",
  "Pantai Timang",
  "Puncak Segoro",
  "Candi Borobudur",
  "Candi Ijo",
  "Pantai Indrayanti",
  "Pantai Nglambor",
  "Pasar Beringharjo",
  "Museum Ullen Sentalu",
  "Museum Gunung Merapi",
  "Pantai Parangtritis",
  "Goa Pindul",
  "Candi Ratu Boko",
  "Pantai Depok Jogja",
  "Pantai Sundak",
  "Hutan Mangrove Kulon Progo",
  "Jogja Bay Pirates Adventure Waterpark",
  "Pantai Sepanjang",
  "Pantai Krakal",
  "Pantai Glagah",
  "Pantai Siung",
  "Pantai Sadranan",
  "Pantai Nguluran",
  "Pantai Samas",
  "Pantai Drini",
  "Air Terjun Sri Gethuk",
  "Candi Sewu",
  "Pantai Wediombo",
  "Pantai Jogan",
  "Pantai Ngrenehan",
  "Pantai Jungwok",
  "Pantai Greweng",
  "Pantai Sedahan",
  "Pantai Watu Kodok",
  "Pantai Kesirat",
  "Pantai Ngandong",
  "Galaxy Waterpark Jogja",
  "Desa Wisata Pulesari",
  "Desa Wisata Tembi",
  "Wisata Kaliurang",
  "Heha Sky View",
  "Taman Sungai Mudal",
  "Pantai Sanglen",
  "Pantai Congot",
  "GunungTangkuban perahu",
  "Jalan Braga",
  "Gedung Sate",
  "Trans Studio Bandung",
  "Taman Hutan Raya Ir. H. Djuanda",
  "Farm House Susu Lembang",
  "Kebun Binatang Bandung",
  "Kawah Putih",
  "Tebing Karaton",
  "Dusun Bambu",
  "Museum Geologi Bandung",
  "Museum Konferensi Asia Afrika",
  "Masjid Raya Bandung",
  "Dago Dreampark",
  "Orchid Forest Cikole",
  "Kawasan Punclut",
  "Alun-Alun Kota Bandung",
  "Museum Sri Baduga",
  "Rabbit Town",
  "Stone Garden Citatah",
  "The Great Asia Africa",
  "Bukit Moko",
  "Gunung Papandayan",
  "Amazing Art World",
  "Gua Belanda",
  "Taman Balai Kota Bandung",
  "Panghegar Waterboom Bandung",
  "Gunung Manglayang",
  "Lembang Park & Zoo",
  "Taman Lalu Lintas Ade Irma Suryani Nasution",
  "Lawangwangi Creative Space",
  "Curug Dago",
  "Kampung Korea Bandung",
  "Kampung Batu Malakasari",
  "Jendela Alam",
  "Curug Tilu Leuwi Opat",
  "Kiara Artha Park",
  "NuArt Sculpture Park",
  "Upside Down World Bandung",
  "Pesona Nirwana Waterpark & Cottages",
  "Taman Lansia",
  "Kampoeng Tulip",
  "Selasar Sunaryo Art Space",
  "Teras Cikapundung BBWS",
  "Museum Barli",
  "Wisata Batu Kuda",
  "Monumen Bandung Lautan Api",
  "Museum Gedung Sate",
  "Monumen Perjuangan Rakyat Jawa Barat",
  "Museum Pos Indonesia",
  "Ciwangun Indah Camp Official",
  "Wot Batu",
  "Curug Batu Templek",
  "Gereja Katedral Santo Petrus Bandung",
  "Museum Mandala Wangsit Siliwangi",
  "Caringin Tilu",
  "Panama Park 825",
  "Sudut Pandang Bandung",
  "Bumi Perkemahan Batu Kuda",
  "Bukit Bintang",
  "Taman Vanda",
  "Taman Budaya Jawa Barat",
  "Curug Bugbrug",
  "Babakan Siliwangi City Forest Path Bandung",
  "Curug Cipanas",
  "Taman Jomblo",
  "Peta Park",
  "Masjid Daarut Tauhiid Bandung",
  "Masjid Agung Trans Studio Bandung",
  "Gereja Tiberias Indonesia Bandung",
  "Tektona Waterpark",
  "Curug Cilengkrang",
  "Jembatan Pasupati",
  "Pasar Baru",
  "Taman Sejarah Bandung",
  "Roemah Seni Sarasvati",
  "Puspa Iptek Sundial",
  "Masjid Salman ITB",
  "Curug Aseupan",
  "Museum Pendidikan Nasional",
  "Water Park Bandung Indah",
  "Curug Anom",
  "Taman Badak",
  "Taman Film",
  "Museum Nike Ardilla",
  "Batununggal Indah Club",
  "Mountain View Golf Club",
  "Gunung Lalakon",
  "Sendang Geulis Kahuripan",
  "Sanghyang Heuleut",
  "Lereng Anteng Panoramic Coffee Place",
  "Masjid Pusdai",
  "Masjid Al-Imtizaj",
  "Situ Cileunca",
  "Sunrise Point Cukul",
  "Sungai Palayangan",
  "Perkebunan Teh Malabar",
  "Pemandian Air Panas Ciater",
  "Observatorium Bosscha",
  "Taman Bunga Cihideung",
  "The Lodge Maribaya",
  "Taman Hutan Raya Ir. H. Juanda",
  "Taman Begonia",
  "Tafso Barn",
  "Curug Luhur Waterfall",
  "Curug Malela",
  "Curug Cimahi",
  "Situ Patenggang",
  "Kawah Rengganis Cibuni",
  "Pemandian Air Panas Cimanggu",
  "Glamping Lakeside Rancabali",
  "Bukit Jamur",
  "Kebun Tanaman Obat Sari Alam",
  "Happyfarm Ciwidey",
  "Saung Angklung Mang Udjo",
  "Taman Kupu-Kupu Cihanjuang",
  "Taman Miniatur Kereta Api",
  "Gua Pawon",
  "Bukit Gantole Cililin",
  "Bandros City Tour",
  "Kyotoku Floating Market",
  "Rainbow Garden",
  "Kota Mini",
  "Chingu Cafe Little Seoul",
  "Candi Gedong Songo",
  "Grand Maerakaca",
  "Kampung Pelangi",
  "Lawang Sewu",
  "Sam Poo Kong Temple",
  "Desa Wisata Lembah Kalipancur",
  "Hutan Wisata Tinjomoyo Semarang",
  "Taman Kasmaran",
  "Pantai Baruna",
  "Pantai Marina",
  "Kampoeng Djadhoel Semarang",
  "Indonesia Kaya Park",
  "Taman Pandanaran",
  "Pura Giri Natha",
  "Wisata Mangrove Tapak",
  "Pantai Cipta",
  "Old City 3D Trick Art Museum",
  "GPIB Immanuel Semarang (Gereja Blenduk)",
  "Taman Srigunting",
  "Semarang Contemporary Art Gallery",
  "Umbul Sidomukti",
  "Saloka Theme Park",
  "Wisata Alam Wana Wisata Penggaron",
  "Masjid Kapal Semarang",
  "Taman Bunga Celosia",
  "Air Terjun Kali Pancur",
  "Wisata Kampung Krisan Clapar",
  "Danau Rawa Pening",
  "Pantai Maron",
  "Water Blaster Bukit Candi Golf",
  "Waduk Jatibarang",
  "Tirto Argo Siwarak",
  "Wisata Lereng Kelir",
  "Kampoeng Rawa",
  "Monumen Palagan Ambarawa",
  "Benteng Pendem",
  "Wisata Eling Bening",
  "Gua Maria Kerep Ambarawa",
  "Museum Kereta Ambarawa",
  "Hutan Pinus Kayon",
  "Kota Lama Semarang",
  "Semarang Chinatown",
  "La Kana Chapel",
  "Jembatan Biru Ambarawa",
  "Goa Rong",
  "Masjid Agung Ungaran",
  "Tugu Muda Semarang",
  "Kampoeng Kopi Banaran",
  "Taman Tabanas",
  "Kampung Tematik Jawi",
  "Kampung Batik Gedong Semarang",
  "Air Terjun Semirang",
  "Obyek Wisata Goa Kreo",
  "Watu Gunung Ungaran",
  "Brown Canyon",
  "Durian Gardens and Tourism Education Watu Simbar",
  "Flower Farm Setiya Aji",
  "Ekowisata Mangrove Wonorejo",
  "Taman Harmoni Keputih",
  "Air Mancur Menari",
  "Taman Prestasi",
  "Monumen Kapal Selam",
  "Taman Kunang-Kunang",
  "Taman Buah Surabaya",
  "Taman Pelangi",
  "Hutan Bambu Keputih",
  "Taman Keputran",
  "Food Junction Grand Pakuwon",
  "Taman Barunawati",
  "Kenjeran Park",
  "Surabaya North Quay",
  "Kebun Bibit Wonorejo",
  "Taman Ekspresi Dan Perpustakaan",
  "Kebun Binatang Surabaya",
  "Rumah Batik",
  "Ciputra Waterpark",
  "Masjid Muhammad Cheng Hoo",
  "Masjid Nasional Al-Akbar",
  "Museum TNI AL Loka Jala Crana",
  "Jembatan Merah",
  "Museum De Javasche Bank",
  "Keraton Surabaya",
  "Klenteng Sanggar Agung",
  "Museum Sepuluh Nopember Kota Surabaya",
  "Monumen Tugu Pahlawan",
  "Surabaya Museum (Gedung Siola)",
  "Museum Kesehatan Dr. Adhyatma",
  "Monumen Jalesveva Jayamahe",
  "Patung Sura dan Buaya",
  "Pantai Ria Kenjeran",
  "Waterpark Kenjeran Surabaya",
  "Balai Kota Surabaya",
  "Patung Buddha Empat Rupa",
  "Monumen Bambu Runcing Surabaya",
  "House of Sampoerna",
  "Atlantis Land Surabaya",
  "Taman Hiburan Rakyat",
  "Taman Mundu",
  "Museum Mpu Tantular",
  "Taman Bungkul",
  "Taman Air Mancur Menari Kenjeran",
  "Taman Flora Bratang Surabaya",
  "Gereja Perawan Maria Tak Berdosa Surabaya",
];

export default placeNames;
